apiVersion: apps/v1
kind: Deployment
metadata:
  name: skruhlik-app
  labels:
    app: skruhlik-app
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: skruhlik-app
  template:
    metadata:
      labels:
        app: skruhlik-app
    spec:
      containers:
      - name: skruhlik-app
        image: 097084951758.dkr.ecr.us-east-1.amazonaws.com/skruhlik-ecr-repository:latest 
        ports:
        - containerPort: 5555  
---
apiVersion: v1
kind: Service
metadata:
  name: skruhlik-app-service
spec:
  selector:
    app: skruhlik-app
  ports:
    - protocol: TCP
      port: 3333  
      targetPort: 5555  
  type: LoadBalancer  
